#!/bin/sh

## run via '. setenv.sh'
##
##

if [ -z "${JAVA_HOME}" ]
then
  echo "JAVA_HOME not set"
  exit 0
fi

if [ ! -x "${JAVA_HOME}/bin/java" ]
then
  echo Cannot find java executable, check JAVA_HOME
  exit 0
fi

EE_HOME=../../../..
LIB=$EE_HOME/lib
ESPER_DEP_LIB=$EE_HOME/lib/esper
ESPERSERVER_DEP_LIB=$EE_HOME/lib/esper-server

CLASSPATH=.
CLASSPATH=$CLASSPATH:../target/classes:.

#  Esper EE jar files (depends on plug-ins activated)
CLASSPATH=$CLASSPATH:$LIB/esper-5.3.0.jar
CLASSPATH=$CLASSPATH:$LIB/esper-eeutil-5.3.0.jar
CLASSPATH=$CLASSPATH:$LIB/esper-cepmgmtsvc-5.3.0.jar
CLASSPATH=$CLASSPATH:$LIB/esper-ceppushsvc-5.3.0.jar
CLASSPATH=$CLASSPATH:$LIB/esper-hqsvc-5.3.0.jar
CLASSPATH=$CLASSPATH:$LIB/esper-jmx-5.3.0.jar
CLASSPATH=$CLASSPATH:$LIB/esper-server-5.3.0.jar
CLASSPATH=$CLASSPATH:$LIB/esper-jdbc-driver-5.3.0.jar
CLASSPATH=$CLASSPATH:$LIB/esper-jdbc-server-5.3.0.jar
CLASSPATH=$CLASSPATH:$LIB/esper-dataflow-sockete2e-5.3.0.jar

#  Esper dependencies
CLASSPATH=$CLASSPATH:$ESPER_DEP_LIB/cglib-nodep-3.1.jar
CLASSPATH=$CLASSPATH:$ESPER_DEP_LIB/commons-logging-1.1.3.jar
CLASSPATH=$CLASSPATH:$ESPER_DEP_LIB/log4j-1.2.17.jar
CLASSPATH=$CLASSPATH:$ESPER_DEP_LIB/antlr-runtime-4.1.jar

#  Esper Server & DDS dependencies
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/jetty-6.1.23.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/javassist.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/jgroups-3.3.3.Final.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/servlet-api-3.0.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/javax.ws.rs.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/org.restlet.ext.httpclient.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/org.restlet.ext.jaxrs.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/org.restlet.ext.servlet.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/org.restlet.ext.slf4j.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/org.restlet.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/jetty-annotations-9.2.9.v20150224.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/jetty-client-9.2.9.v20150224.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/jetty-continuation-9.2.9.v20150224.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/jetty-deploy-9.2.9.v20150224.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/jetty-http-9.2.9.v20150224.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/jetty-io-9.2.9.v20150224.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/jetty-jaas-9.2.9.v20150224.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/jetty-jmx-9.2.9.v20150224.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/jetty-plus-9.2.9.v20150224.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/jetty-proxy-9.2.9.v20150224.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/jetty-rewrite-9.2.9.v20150224.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/jetty-security-9.2.9.v20150224.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/jetty-server-9.2.9.v20150224.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/jetty-servlet-9.2.9.v20150224.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/jetty-servlets-9.2.9.v20150224.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/jetty-util-9.2.9.v20150224.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/jetty-webapp-9.2.9.v20150224.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/jetty-xml-9.2.9.v20150224.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/websocket-api-9.2.9.v20150224.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/websocket-common-9.2.9.v20150224.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/websocket-server-9.2.9.v20150224.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/websocket-servlet-9.2.9.v20150224.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/activemq-all-5.11.1.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/geronimo-j2ee-management_1.1_spec-1.0.1.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/geronimo-jms_1.1_spec-1.1.1.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/gson-2.3.1.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/xstream-1.4.4.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/slf4j-api-1.7.2.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/slf4j-log4j12-1.7.2.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/commons-codec-1.6.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/commons-lang-2.6.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/httpclient-4.4.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/httpcore-4.4.jar
CLASSPATH=$CLASSPATH:$ESPERSERVER_DEP_LIB/groovy-all-2.4.1.jar

export CLASSPATH="$CLASSPATH"
